#![cfg(feature = "zarr")]

//! OME-Zarr / OME-NGFF reader tests.
//!
//! These exercise `OmeZarrReader` against deterministic samples generated by
//! `scripts/gen_zarr_sample.py`. The samples encode a known pixel pattern so
//! reads can be verified bitwise. Tests are skipped when the samples are absent
//! (the generator needs Python + zarr).

use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use bioformats::common::metadata::DimensionOrder;
use bioformats::common::pixel_type::PixelType;
use bioformats::common::reader::FormatReader;
use bioformats::formats::zarr::OmeZarrReader;
use bioformats::Memoizer;

fn sample_dir(name: &str) -> Option<PathBuf> {
    let p = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/zarr")
        .join(name);
    if p.exists() {
        Some(p)
    } else {
        None
    }
}

/// Deterministic pattern written by the generator:
/// val(t,c,z,y,x,level) = (level*10000 + t*7 + c*1000 + z*100 + y*10 + x) & 0xFFFF
fn pat(t: u32, c: u32, z: u32, y: u32, x: u32, level: u32) -> u16 {
    ((level * 10000 + t * 7 + c * 1000 + z * 100 + y * 10 + x) & 0xFFFF) as u16
}

fn le_u16(bytes: &[u8], i: usize) -> u16 {
    u16::from_le_bytes([bytes[2 * i], bytes[2 * i + 1]])
}

fn tmp_zarr_dir(name: &str) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    std::env::temp_dir().join(format!("bioformats_rs_{name}_{nonce}.zarr"))
}

#[test]
fn plain_root_zarr_array_uses_tczyx_shape_fallback() {
    let dir = tmp_zarr_dir("plain_root_array");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(
        dir.join(".zarray"),
        r#"{"zarr_format":2,"shape":[2,3],"chunks":[2,3],"dtype":"<u2","compressor":null,"fill_value":0,"order":"C","filters":null}"#,
    )
    .unwrap();
    std::fs::write(dir.join(".zattrs"), "{}").unwrap();
    let pixels = [1u16, 2, 3, 4, 5, 6]
        .iter()
        .flat_map(|v| v.to_le_bytes())
        .collect::<Vec<_>>();
    std::fs::write(dir.join("0.0"), pixels).unwrap();

    let mut r = OmeZarrReader::new();
    r.set_id(&dir).unwrap();
    let m = r.metadata();
    assert_eq!(
        (m.size_x, m.size_y, m.size_z, m.size_c, m.size_t),
        (3, 2, 1, 1, 1)
    );
    assert_eq!(m.pixel_type, PixelType::Uint16);
    assert_eq!(m.dimension_order, DimensionOrder::XYZCT);
    let buf = r.open_bytes(0).unwrap();
    let got = (0..6).map(|i| le_u16(&buf, i)).collect::<Vec<_>>();
    assert_eq!(got, vec![1, 2, 3, 4, 5, 6]);

    let _ = std::fs::remove_dir_all(&dir);
}

/// Hand-built two-level multiscales group (no Python/zarr generator needed):
/// `.zattrs` at the root declares `datasets` `0` (4x4) and `1` (2x2), each a
/// plain v2 array under its own subdirectory.
fn write_two_level_multiscales(dir: &Path) {
    std::fs::create_dir_all(dir).unwrap();
    std::fs::write(dir.join(".zgroup"), r#"{"zarr_format":2}"#).unwrap();
    std::fs::write(
        dir.join(".zattrs"),
        r#"{"multiscales":[{"axes":[{"name":"y","type":"space"},{"name":"x","type":"space"}],"datasets":[{"path":"0"},{"path":"1"}]}]}"#,
    )
    .unwrap();

    let level0 = dir.join("0");
    std::fs::create_dir_all(&level0).unwrap();
    std::fs::write(
        level0.join(".zarray"),
        r#"{"zarr_format":2,"shape":[4,4],"chunks":[4,4],"dtype":"<u2","compressor":null,"fill_value":0,"order":"C","filters":null}"#,
    )
    .unwrap();
    let pixels0: Vec<u8> = (1u16..=16)
        .flat_map(|v| v.to_le_bytes())
        .collect::<Vec<_>>();
    std::fs::write(level0.join("0.0"), pixels0).unwrap();

    let level1 = dir.join("1");
    std::fs::create_dir_all(&level1).unwrap();
    std::fs::write(
        level1.join(".zarray"),
        r#"{"zarr_format":2,"shape":[2,2],"chunks":[2,2],"dtype":"<u2","compressor":null,"fill_value":0,"order":"C","filters":null}"#,
    )
    .unwrap();
    let pixels1: Vec<u8> = (101u16..=104)
        .flat_map(|v| v.to_le_bytes())
        .collect::<Vec<_>>();
    std::fs::write(level1.join("0.0"), pixels1).unwrap();
}

#[test]
fn flattened_resolutions_toggle_matches_java_setflattenedresolutions() {
    let dir = tmp_zarr_dir("flatten_toggle");
    let _ = std::fs::remove_dir_all(&dir);
    write_two_level_multiscales(&dir);

    // Default (Java's setFlattenedResolutions(true)): each pyramid level is
    // its own top-level series.
    let mut flattened = OmeZarrReader::new();
    flattened.set_id(&dir).unwrap();
    assert_eq!(flattened.series_count(), 2);
    assert_eq!(flattened.resolution_count(), 1);
    let m0 = flattened.metadata();
    assert_eq!((m0.size_x, m0.size_y), (4, 4));
    let b0 = flattened.open_bytes(0).unwrap();
    assert_eq!(
        (0..16).map(|i| le_u16(&b0, i)).collect::<Vec<_>>(),
        (1u16..=16).collect::<Vec<_>>()
    );
    flattened.set_series(1).unwrap();
    assert_eq!(flattened.resolution_count(), 1);
    let m1 = flattened.metadata();
    assert_eq!((m1.size_x, m1.size_y), (2, 2));
    let b1 = flattened.open_bytes(0).unwrap();
    assert_eq!(
        (0..4).map(|i| le_u16(&b1, i)).collect::<Vec<_>>(),
        (101u16..=104).collect::<Vec<_>>()
    );

    // setFlattenedResolutions(false): the multiscales image stays one series,
    // with levels reachable via resolution_count()/set_resolution().
    let mut grouped = OmeZarrReader::new();
    grouped.set_flattened_resolutions(false);
    grouped.set_id(&dir).unwrap();
    assert_eq!(grouped.series_count(), 1);
    assert_eq!(grouped.resolution_count(), 2);
    let m0 = grouped.metadata();
    assert_eq!((m0.size_x, m0.size_y), (4, 4));
    grouped.set_resolution(1).unwrap();
    let m1 = grouped.metadata();
    assert_eq!((m1.size_x, m1.size_y), (2, 2));
    let b1 = grouped.open_bytes(0).unwrap();
    assert_eq!(
        (0..4).map(|i| le_u16(&b1, i)).collect::<Vec<_>>(),
        (101u16..=104).collect::<Vec<_>>()
    );

    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn memoizer_cache_hit_detects_zarr_directory() {
    let dir = tmp_zarr_dir("memoizer_plain_root_array");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(
        dir.join(".zarray"),
        r#"{"zarr_format":2,"shape":[2,3],"chunks":[2,3],"dtype":"<u2","compressor":null,"fill_value":0,"order":"C","filters":null}"#,
    )
    .unwrap();
    std::fs::write(dir.join(".zattrs"), "{}").unwrap();
    let pixels = [1u16, 2, 3, 4, 5, 6]
        .iter()
        .flat_map(|v| v.to_le_bytes())
        .collect::<Vec<_>>();
    std::fs::write(dir.join("0.0"), pixels).unwrap();

    let first = Memoizer::open(&dir).unwrap();
    assert_eq!(first.metadata().size_x, 3);
    let second = Memoizer::open(&dir).unwrap();
    assert_eq!(second.metadata().size_y, 2);

    let cache = dir.with_file_name(format!(
        ".{}.bfmemo",
        dir.file_name().unwrap().to_string_lossy()
    ));
    let _ = std::fs::remove_file(cache);
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn single_multiscales_dimensions_and_resolutions() {
    let Some(dir) = sample_dir("sample.ome.zarr") else {
        eprintln!("skipping: testdata/zarr/sample.ome.zarr absent");
        return;
    };
    let mut r = OmeZarrReader::new();
    r.set_id(&dir).unwrap();

    assert_eq!(r.series_count(), 1, "one multiscales image == one series");
    let m = r.metadata();
    assert_eq!((m.size_x, m.size_y), (32, 32));
    assert_eq!(m.size_z, 3);
    assert_eq!(m.size_c, 2);
    assert_eq!(m.size_t, 1);
    assert_eq!(m.pixel_type, PixelType::Uint16);
    assert_eq!(m.image_count, 6);
    assert_eq!(m.dimension_order, DimensionOrder::XYZCT);
    assert!(m.is_little_endian);

    assert_eq!(r.resolution_count(), 2, "two pyramid levels");
}

#[test]
fn single_multiscales_bitwise_pixels_level0() {
    let Some(dir) = sample_dir("sample.ome.zarr") else {
        return;
    };
    let mut r = OmeZarrReader::new();
    r.set_id(&dir).unwrap();

    // Dimension order XYZCT => plane index varies Z fastest, then C, then T.
    // plane 4 => z=1, c=1, t=0.
    let plane = 4u32;
    let z = plane % 3;
    let c = plane / 3;
    let t = 0;
    assert_eq!((z, c), (1, 1));

    let buf = r.open_bytes(plane).unwrap();
    assert_eq!(buf.len(), 32 * 32 * 2);
    for y in 0..32u32 {
        for x in 0..32u32 {
            let got = le_u16(&buf, (y * 32 + x) as usize);
            assert_eq!(
                got,
                pat(t, c, z, y, x, 0),
                "mismatch at z{z} c{c} y{y} x{x}"
            );
        }
    }
}

#[test]
fn single_multiscales_region_read() {
    let Some(dir) = sample_dir("sample.ome.zarr") else {
        return;
    };
    let mut r = OmeZarrReader::new();
    r.set_id(&dir).unwrap();

    // plane 0 => z=0, c=0, t=0. Read a 5x4 region at (x=10, y=20).
    let (rx, ry, rw, rh) = (10u32, 20u32, 5u32, 4u32);
    let buf = r.open_bytes_region(0, rx, ry, rw, rh).unwrap();
    assert_eq!(buf.len() as u32, rw * rh * 2);
    for j in 0..rh {
        for i in 0..rw {
            let got = le_u16(&buf, (j * rw + i) as usize);
            assert_eq!(got, pat(0, 0, 0, ry + j, rx + i, 0));
        }
    }
}

#[test]
fn single_multiscales_resolution_level1() {
    let Some(dir) = sample_dir("sample.ome.zarr") else {
        return;
    };
    let mut r = OmeZarrReader::new();
    r.set_id(&dir).unwrap();
    r.set_resolution(1).unwrap();

    let m = r.metadata();
    assert_eq!((m.size_x, m.size_y), (16, 16), "level 1 is 16x16");
    assert_eq!(m.size_z, 3);
    assert_eq!(m.size_c, 2);

    // plane 0 => z=0,c=0. Level-1 pattern uses level=1.
    let buf = r.open_bytes(0).unwrap();
    assert_eq!(buf.len(), 16 * 16 * 2);
    for y in 0..16u32 {
        for x in 0..16u32 {
            let got = le_u16(&buf, (y * 16 + x) as usize);
            assert_eq!(got, pat(0, 0, 0, y, x, 1));
        }
    }
}

#[test]
fn single_multiscales_ome_channels_and_physical_sizes() {
    let Some(dir) = sample_dir("sample.ome.zarr") else {
        return;
    };
    let mut r = OmeZarrReader::new();
    r.set_id(&dir).unwrap();

    let ome = r.ome_metadata().expect("ome metadata");
    assert_eq!(ome.images.len(), 1);
    let img = &ome.images[0];

    // Physical sizes from level-0 scale [t=1, c=1, z=2.0, y=0.5, x=0.5] (µm).
    assert_eq!(img.physical_size_x, Some(0.5));
    assert_eq!(img.physical_size_y, Some(0.5));
    assert_eq!(img.physical_size_z, Some(2.0));

    // omero channels: DAPI (blue) + GFP (green).
    assert_eq!(img.channels.len(), 2);
    assert_eq!(img.channels[0].name.as_deref(), Some("DAPI"));
    assert_eq!(img.channels[1].name.as_deref(), Some("GFP"));
    // 0000FF -> RGBA 0x0000FFFF = 65535
    assert_eq!(img.channels[0].color, Some(0x0000_FFFFu32 as i32));
    // 00FF00 -> RGBA 0x00FF00FF
    assert_eq!(img.channels[1].color, Some(0x00FF_00FFu32 as i32));
}

#[test]
fn multi_image_bioformats2raw_layout() {
    let Some(dir) = sample_dir("multi.ome.zarr") else {
        eprintln!("skipping: testdata/zarr/multi.ome.zarr absent");
        return;
    };
    let mut r = OmeZarrReader::new();
    r.set_id(&dir).unwrap();

    assert_eq!(r.series_count(), 2, "two sub-image multiscales groups");

    // Series 0: 8x8, 1 channel.
    r.set_series(0).unwrap();
    let m0 = r.metadata();
    assert_eq!((m0.size_x, m0.size_y), (8, 8));
    assert_eq!(m0.size_c, 1);
    assert_eq!(m0.size_t, 1);
    let b0 = r.open_bytes(0).unwrap();
    assert_eq!(b0.len(), 8 * 8 * 2);
    assert_eq!(le_u16(&b0, 0), pat(0, 0, 0, 0, 0, 0));
    assert_eq!(le_u16(&b0, (3 * 8 + 5) as usize), pat(0, 0, 0, 3, 5, 0));

    // Series 1: 6x4, 2 channels, 2 timepoints.
    r.set_series(1).unwrap();
    let m1 = r.metadata();
    assert_eq!((m1.size_x, m1.size_y), (6, 4));
    assert_eq!(m1.size_c, 2);
    assert_eq!(m1.size_t, 2);
    assert_eq!(m1.image_count, 4);

    // Order XYZCT: plane fastest Z(=1) then C then T. plane 1 => z0,c1,t0.
    let b1 = r.open_bytes(1).unwrap();
    assert_eq!(b1.len(), 6 * 4 * 2);
    for y in 0..4u32 {
        for x in 0..6u32 {
            let got = le_u16(&b1, (y * 6 + x) as usize);
            assert_eq!(got, pat(0, 1, 0, y, x, 0), "series1 c1 y{y} x{x}");
        }
    }
}

/// Real-world OME-NGFF v0.4 sample from the IDR (idr0062A, image 6001240),
/// downloaded by `scripts/download_zarr_sample.sh`. It is a 4D (c,z,y,x) uint16
/// multiscales image with 3 pyramid levels and two omero channels
/// (LaminB1 / Dapi). Ground-truth pixel values were cross-checked with the
/// Python `zarr` library. Skips gracefully when the sample is absent.
#[test]
fn real_idr0062a_multiscales() {
    let Some(dir) = sample_dir("idr0062A_6001240.ome.zarr") else {
        eprintln!(
            "skipping: testdata/zarr/idr0062A_6001240.ome.zarr absent \
            (run scripts/download_zarr_sample.sh)"
        );
        return;
    };
    let mut r = OmeZarrReader::new();
    r.set_id(&dir).unwrap();

    // One multiscales image == one series, 3 pyramid levels.
    assert_eq!(r.series_count(), 1, "one multiscales image == one series");
    assert_eq!(r.resolution_count(), 3, "three pyramid levels");

    // Level 0 dims: shape [c=2, z=236, y=275, x=271].
    let m = r.metadata();
    assert_eq!((m.size_x, m.size_y), (271, 275));
    assert_eq!(m.size_z, 236);
    assert_eq!(m.size_c, 2);
    assert_eq!(m.size_t, 1);
    assert_eq!(m.pixel_type, PixelType::Uint16);
    assert_eq!(m.image_count, 236 * 2, "Z*C*T planes");
    // axes c,z,y,x reversed -> X,Y,Z,C tail => XYZCT.
    assert_eq!(m.dimension_order, DimensionOrder::XYZCT);
    assert!(m.is_little_endian);

    // Level-0 pixels. Order XYZCT => plane = z + Z*(c + C*t).
    // plane 0 => z=0, c=0, t=0. Ground truth (Python zarr): a0[0,0,0,0]=8,
    // first row a0[0,0,0,0:4] = [8, 9, 8, 10].
    let p0 = r.open_bytes(0).unwrap();
    assert_eq!(p0.len(), 271 * 275 * 2);
    assert_eq!(le_u16(&p0, 0), 8);
    let row0: Vec<u16> = (0..4).map(|x| le_u16(&p0, x)).collect();
    assert_eq!(row0, vec![8, 9, 8, 10]);

    // A region read on plane z=118, c=0 => plane index 118.
    // Ground truth: a0[0,118,50:60,50:60].sum()=993, first row
    // a0[0,118,50,50:60] = [23, 8, 8, 9, 8, 7, 9, 8, 45, 8].
    let plane_z118_c0 = 118u32;
    let reg = r.open_bytes_region(plane_z118_c0, 50, 50, 10, 10).unwrap();
    assert_eq!(reg.len(), 10 * 10 * 2);
    let reg_row0: Vec<u16> = (0..10).map(|i| le_u16(&reg, i)).collect();
    assert_eq!(reg_row0, vec![23, 8, 8, 9, 8, 7, 9, 8, 45, 8]);
    let reg_sum: u64 = (0..100).map(|i| le_u16(&reg, i) as u64).sum();
    assert_eq!(reg_sum, 993, "region checksum vs Python ground truth");

    // c=1 plane: plane = z + Z*c = 118 + 236 = 354. a0[1,118,100,100]=26.
    let plane_z118_c1 = 118 + 236u32;
    let p354 = r.open_bytes(plane_z118_c1).unwrap();
    assert_eq!(le_u16(&p354, (100 * 271 + 100) as usize), 26);

    // Pyramid levels downsample x/y but keep z,c. Ground truth top-left pixels:
    // L1 a1[0,0,0,0]=9, L2 a2[0,0,0,0]=28.
    r.set_resolution(1).unwrap();
    let m1 = r.metadata();
    assert_eq!((m1.size_x, m1.size_y), (135, 137));
    assert_eq!((m1.size_z, m1.size_c), (236, 2));
    let l1 = r.open_bytes(0).unwrap();
    assert_eq!(l1.len(), 135 * 137 * 2);
    assert_eq!(le_u16(&l1, 0), 9);

    r.set_resolution(2).unwrap();
    let m2 = r.metadata();
    assert_eq!((m2.size_x, m2.size_y), (67, 68));
    let l2 = r.open_bytes(0).unwrap();
    assert_eq!(le_u16(&l2, 0), 28);

    // OME metadata: physical sizes from level-0 scale
    // [c=1.0, z=0.5002.., y=0.3604.., x=0.3604..] micrometer, and two omero
    // channels LaminB1 (blue 0000FF) + Dapi (yellow FFFF00).
    let ome = r.ome_metadata().expect("ome metadata");
    assert_eq!(ome.images.len(), 1);
    let img = &ome.images[0];
    let approx = |a: Option<f64>, b: f64| (a.unwrap() - b).abs() < 1e-6;
    assert!(approx(img.physical_size_x, 0.3603981534640209), "phys x");
    assert!(approx(img.physical_size_y, 0.3603981534640209), "phys y");
    assert!(approx(img.physical_size_z, 0.5002025531914894), "phys z");
    assert_eq!(img.channels.len(), 2);
    assert_eq!(img.channels[0].name.as_deref(), Some("LaminB1"));
    assert_eq!(img.channels[1].name.as_deref(), Some("Dapi"));
    // 0000FF -> RGBA 0x0000FFFF; FFFF00 -> 0xFFFF00FF.
    assert_eq!(img.channels[0].color, Some(0x0000_FFFFu32 as i32));
    assert_eq!(img.channels[1].color, Some(0xFFFF_00FFu32 as i32));

    // The registry auto-detection path must also open this real directory.
    let mut auto =
        bioformats::ImageReader::open(&dir).expect("auto-detect real OME-Zarr directory");
    assert_eq!(auto.series_count(), 1);
    assert_eq!(auto.metadata().size_x, 271);
    assert_eq!(le_u16(&auto.open_bytes(0).unwrap(), 0), 8);
}

#[test]
fn opens_via_image_reader_autodetection() {
    let Some(dir) = sample_dir("sample.ome.zarr") else {
        return;
    };
    let mut r = bioformats::ImageReader::open(&dir).expect("auto-detect OME-Zarr directory");
    assert_eq!(r.series_count(), 1);
    assert_eq!(r.metadata().size_x, 32);
    let buf = r.open_bytes(0).unwrap();
    assert_eq!(le_u16(&buf, 0), pat(0, 0, 0, 0, 0, 0));
}
