[package]
name = "bench-read"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "bench_rust"
path = "bench_rust.rs"

[[bin]]
name = "bench_subset_rust"
path = "bench_subset_rust.rs"

[[bin]]
name = "bench_profile_rust"
path = "bench_profile_rust.rs"

[dependencies]
bioformats = { path = ".." }
